language: python
python:
- '3.6'
script:
- echo Good
deploy:
  provider: pypi
  user: ZiggerZZ
  password:
    secure: GSFvKITkwrroJVn/2MJmxKrV5wPNg7m65UOriaU5w/vPeF4jJv89+njGoOhrUh/5iyQ/FNV/LGR1q3pvAZByGMmwU+hR9EV2Ub4WXEObjCtxZTAcf7AEguAYgX5p7VnGXOJNDd9P2a0t5tXcehu57SeSHRVG/fPpIHGsYkrMqw5C2zmbKH+mXhharusli0WwopsuofgAcLtkl4IqSzfWD7m4FbGgYL6qjBvqpkQMg4AFlokPYD8YAgI12Ktc0PVLFojCRayTPN4UN4dprYyOsY4uMr8bug83T1rw2RFo+lakhuCkcK0fQe1lY0WsowB8ZIjuLk0lzIQ84qJ7lkPlIbKGkl8sthobKrnoaof3KfBdN3E9Z9kUm1GCGhrQblkqFL1D8XIxjoiA4xXdGpMTYpYye0t38FH0Qqryxcb4oaFAW6TQ0JWmTogKrErSpOiS6HpvySW6Cf/3M8QZVXpxDH4me4fMwBNK98ojB1QVH+qx+LRJuWQt4kMGOjDNgXg6c4kTqoDf6jBfx/3H5PTx1O7RcQ9UXEU8hv1NxPktH9Uq1z5eX3x1rH6ia4C4gWpfwtzR7B2Omy8VVZDFeuQ4CxidIi2aosT7X3J8Y+h9bEVegT+1KsWfnnRU9LTEm+jEC4/+vwO1IMQJhL4UbXdFQ8lkryUIcBmpEyhmPdIbW70=
  distributions: sdist bdist_wheel
  edge: true
  on:
    python: 3.6
    tags: true
